### ISSUE TITLE
Need to Style APA citation for proper indent

### ISSUE THREAD

**Issue by jgmac1106** [Zegnat/php-greg-cites#1]
I usually do this:
.apa {
    padding-left: 22px ;
  text-indent: -22px ;
}

Didn't want to do inline styling  (cool with it if you are) but didn't see a stylesheet so made issue rather than filing PR.

**Comment by Zegnat** [comment]
I wanted to keep it easy to copy the HTML snippet by itself, which is why I am also using inline styling for setting (and unsetting) some of the italics.

So I’m leaning towards using inline styling. Unless you see a use-case that means we can’t do that?

**Comment by jgmac1106** [comment]
no I am okay with inline just know some people aren't fans.
