### ISSUE TITLE
Additional APA formats

### ISSUE THREAD

**Issue by jgmac1106** [Zegnat/php-greg-cites#4]
Book
<pre>&lt;p class="h-cite"&gt;&lt;span class="p-author h-card"&gt;Gee, James, Paul &lt;/span&gt; &lt;time class="dt-published"&gt;(2018)&lt;/time&gt;. &lt;span class="p-publication" style="em"&gt;Anti-education era: <i>Creating Smarter Students Through Digital Learning</i>. &lt;/span&gt;.&lt;span class="p-locality"&gt;New York&lt;/span&gt;: &lt;span class="p-publisher&gt;Macmillan&lt;/span&gt;&lt;/p&gt;</pre>
Chapter in Book
<pre>&lt;p class="h-cite"&gt;&lt;span class="p-author h-card"&gt;Family Name, Given Name&lt;/span&gt;&lt;time class="dt-published"&gt;(2018)&lt;/time&gt;.&lt;span class="p-name"&gt;Chapter title&lt;/a&gt;. In &lt;span class="h-card"&gt;Editor Given Name first initial, Family Name&lt;/span&gt; (eds.)  &lt;span class="p-name" style="em"&gt;Title of Book&lt;/span&gt;(pages of chapter).&lt;span class="p-locality"&gt;New York&lt;/span&gt;: &lt;span class="p-publisher&gt;Macmillan&lt;/span&gt;&lt;/p&gt;</pre>

**Comment by Zegnat** [comment]
These would be used for `@BOOK` and `@INBOOK` BibTeX records?

**Comment by jgmac1106** [comment]
Yes. What guide are you using for BibTex record? I will convert the citation to the BibTex field.

**Comment by Zegnat** [comment]
> What guide are you using for BibTex record?

Google. Hahaha. In this case, [these entry types](https://nwalsh.com/tex/texhelp/bibtx-7.html).

I am going to see if I can more easily split the records on their type. That will make it easier for the template files to contain different handling for the different types.

**Comment by Zegnat** [comment]
@jgmac1106 do you have the matching BibTeX that you would expect for the example HTML?

I have come up with the following, but not 100% sure these are as you would expect them.

```bibtex
@book{gee2018anti,
  title={Anti-education era: Creating Smarter Students Through Digital Learning},
  author={Gee, James Paul},
  year={2018},
  publisher={Macmillan},
  address={New York}
}
```

```bibtex
@inbook{family2018title,
  author = {Family Name, Given Name},
  title = {Title of Book},
  chapter = {Chapter title},
  pages = {pages of chapter},
  publisher = {Macmillan},
  year = 2018,
  editor = {Editor Given Name first initial, Family Name},
  address = {New York}
}
```

These examples were based on Walsh’ [Help On BibTeX](https://nwalsh.com/tex/texhelp/BibTeX.html) (as linked before) and the Verbosus’ [BibTeX Style Examples](https://www.verbosus.com/bibtex-style-examples.html).

**Comment by Zegnat** [comment]
Closing after commit 5946774. Open new issues if there are problems with the produced HTML.
